### ISSUE TITLE
Setup.py Bug in cookie cutter

### ISSUE THREAD

**Issue by someshsingh22** [SforAiDl/decepticonlp#16]
According to the instructions in CONTRIBUTING.rst from the cookie-cutter template
There is an error in setting the local environment up -

```bash
python setup.py
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    with open("README.rst") as readme_file:
FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
```

The issue remains the same for
```bash
python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    with open("README.rst") as readme_file:
FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
```
Implement the 'README.rst'

**Comment by rajaswa** [comment]
temporary fix done in #26 
closing the issue
